// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi keptn api

    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 0.1.0

    Consumes:
    - application/cloudevents+json

    Produces:
    - application/cloudevents+json

swagger:meta
*/
package restapi
