// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi keptn api

    Schemes:
      https
    Host: localhost
    BasePath: /v1
    Version: develop

    Consumes:
    - application/cloudevents+json

    Produces:
    - application/json

swagger:meta
*/
package restapi
