// Code generated by go-swagger; DO NOT EDIT.

package configure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostConfigureBridgeExposeParams creates a new PostConfigureBridgeExposeParams object
// no default values defined in spec.
func NewPostConfigureBridgeExposeParams() PostConfigureBridgeExposeParams {

	return PostConfigureBridgeExposeParams{}
}

// PostConfigureBridgeExposeParams contains all the bound params for the post configure bridge expose operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostConfigureBridgeExpose
type PostConfigureBridgeExposeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Flag for exposing the bridge
	  In: body
	*/
	Expose bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConfigureBridgeExposeParams() beforehand.
func (o *PostConfigureBridgeExposeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body bool
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("expose", "body", "", err))
		} else {
			// no validation required on inline body
			o.Expose = body
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
