// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetEventsURL generates an URL for the get events operation
type GetEventsURL struct {
	KeptnContext *string
	NextPageKey  *string
	PageSize     *int64
	Project      *string
	Service      *string
	Stage        *string
	Type         *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetEventsURL) WithBasePath(bp string) *GetEventsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetEventsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetEventsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/event"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var keptnContext string
	if o.KeptnContext != nil {
		keptnContext = *o.KeptnContext
	}
	if keptnContext != "" {
		qs.Set("keptnContext", keptnContext)
	}

	var nextPageKey string
	if o.NextPageKey != nil {
		nextPageKey = *o.NextPageKey
	}
	if nextPageKey != "" {
		qs.Set("nextPageKey", nextPageKey)
	}

	var pageSize string
	if o.PageSize != nil {
		pageSize = swag.FormatInt64(*o.PageSize)
	}
	if pageSize != "" {
		qs.Set("pageSize", pageSize)
	}

	var project string
	if o.Project != nil {
		project = *o.Project
	}
	if project != "" {
		qs.Set("project", project)
	}

	var service string
	if o.Service != nil {
		service = *o.Service
	}
	if service != "" {
		qs.Set("service", service)
	}

	var stage string
	if o.Stage != nil {
		stage = *o.Stage
	}
	if stage != "" {
		qs.Set("stage", stage)
	}

	var typeVar string
	if o.Type != nil {
		typeVar = *o.Type
	}
	if typeVar != "" {
		qs.Set("type", typeVar)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetEventsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetEventsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetEventsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetEventsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetEventsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetEventsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
