// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/keptn/keptn/api/models"
)

// ServiceHandlerFunc turns a function with the right signature into a service handler
type ServiceHandlerFunc func(ServiceParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ServiceHandlerFunc) Handle(params ServiceParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ServiceHandler interface for that can handle valid service params
type ServiceHandler interface {
	Handle(ServiceParams, *models.Principal) middleware.Responder
}

// NewService creates a new http.Handler for the service operation
func NewService(ctx *middleware.Context, handler ServiceHandler) *Service {
	return &Service{Context: ctx, Handler: handler}
}

/*Service swagger:route POST /service service service

Forwards the received service event to the eventbroker

*/
type Service struct {
	Context *middleware.Context
	Handler ServiceHandler
}

func (o *Service) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewServiceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
