// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/cloudevents+json",
    "application/json"
  ],
  "produces": [
    "application/cloudevents+json",
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "mongodb-datastore",
    "version": "0.1.0"
  },
  "basePath": "/",
  "paths": {
    "/events": {
      "get": {
        "tags": [
          "event"
        ],
        "summary": "Gets events from the data store",
        "operationId": "getEvents",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/KeptnContextExtendedCE"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "event"
        ],
        "summary": "Saves an event to the datastore",
        "operationId": "saveEvent",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/KeptnContextExtendedCE"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/events/id/{id}": {
      "get": {
        "tags": [
          "event"
        ],
        "summary": "Gets events from the data store",
        "operationId": "getEvent",
        "parameters": [
          {
            "type": "string",
            "description": "ID of the event to get",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/KeptnContextExtendedCE"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/events/type/newartifact": {
      "get": {
        "tags": [
          "event"
        ],
        "summary": "Gets new artifact events from the data store",
        "operationId": "getNewArtifactEvents",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/KeptnContextExtendedCE"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/logs": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "gets the logs from the datastore",
        "operationId": "getLogs",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/LogEntry"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "logs"
        ],
        "summary": "Saves a log to the datastore",
        "operationId": "saveLog",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/LogEntry"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/logs/eventId/{eventId}": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "Get logs by eventId",
        "operationId": "getLogsByEventId",
        "parameters": [
          {
            "type": "string",
            "description": "EventId of the event the logs belog to",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/LogEntry"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "KeptnContextExtendedCE": {
      "allOf": [
        {
          "$ref": "https://raw.githubusercontent.com/cloudevents/spec/v0.2/spec.json#/definitions/event"
        },
        {
          "type": "object",
          "properties": {
            "shkeptncontext": {
              "type": "string"
            }
          }
        }
      ]
    },
    "LogEntry": {
      "type": "object",
      "properties": {
        "eventId": {
          "type": "string"
        },
        "keptnContext": {
          "type": "string"
        },
        "keptnService": {
          "type": "string"
        },
        "logLevel": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/cloudevents+json",
    "application/json"
  ],
  "produces": [
    "application/cloudevents+json",
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "mongodb-datastore",
    "version": "0.1.0"
  },
  "basePath": "/",
  "paths": {
    "/events": {
      "get": {
        "tags": [
          "event"
        ],
        "summary": "Gets events from the data store",
        "operationId": "getEvents",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "type": "object",
                    "required": [
                      "specversion",
                      "id",
                      "type",
                      "source"
                    ],
                    "properties": {
                      "contenttype": {
                        "type": "string"
                      },
                      "data": {
                        "type": [
                          "object",
                          "string"
                        ]
                      },
                      "extensions": {
                        "type": "object"
                      },
                      "id": {
                        "type": "string"
                      },
                      "source": {
                        "type": "string",
                        "format": "uri-reference"
                      },
                      "specversion": {
                        "type": "string"
                      },
                      "time": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "type": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "properties": {
                      "shkeptncontext": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "event"
        ],
        "summary": "Saves an event to the datastore",
        "operationId": "saveEvent",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "allOf": [
                {
                  "type": "object",
                  "required": [
                    "specversion",
                    "id",
                    "type",
                    "source"
                  ],
                  "properties": {
                    "contenttype": {
                      "type": "string"
                    },
                    "data": {
                      "type": [
                        "object",
                        "string"
                      ]
                    },
                    "extensions": {
                      "type": "object"
                    },
                    "id": {
                      "type": "string"
                    },
                    "source": {
                      "type": "string",
                      "format": "uri-reference"
                    },
                    "specversion": {
                      "type": "string"
                    },
                    "time": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "type": {
                      "type": "string"
                    }
                  }
                },
                {
                  "type": "object",
                  "properties": {
                    "shkeptncontext": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/events/id/{id}": {
      "get": {
        "tags": [
          "event"
        ],
        "summary": "Gets events from the data store",
        "operationId": "getEvent",
        "parameters": [
          {
            "type": "string",
            "description": "ID of the event to get",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "type": "object",
                    "required": [
                      "specversion",
                      "id",
                      "type",
                      "source"
                    ],
                    "properties": {
                      "contenttype": {
                        "type": "string"
                      },
                      "data": {
                        "type": [
                          "object",
                          "string"
                        ]
                      },
                      "extensions": {
                        "type": "object"
                      },
                      "id": {
                        "type": "string"
                      },
                      "source": {
                        "type": "string",
                        "format": "uri-reference"
                      },
                      "specversion": {
                        "type": "string"
                      },
                      "time": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "type": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "properties": {
                      "shkeptncontext": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/events/type/newartifact": {
      "get": {
        "tags": [
          "event"
        ],
        "summary": "Gets new artifact events from the data store",
        "operationId": "getNewArtifactEvents",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "type": "object",
                    "required": [
                      "specversion",
                      "id",
                      "type",
                      "source"
                    ],
                    "properties": {
                      "contenttype": {
                        "type": "string"
                      },
                      "data": {
                        "type": [
                          "object",
                          "string"
                        ]
                      },
                      "extensions": {
                        "type": "object"
                      },
                      "id": {
                        "type": "string"
                      },
                      "source": {
                        "type": "string",
                        "format": "uri-reference"
                      },
                      "specversion": {
                        "type": "string"
                      },
                      "time": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "type": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "properties": {
                      "shkeptncontext": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/logs": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "gets the logs from the datastore",
        "operationId": "getLogs",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "eventId": {
                    "type": "string"
                  },
                  "keptnContext": {
                    "type": "string"
                  },
                  "keptnService": {
                    "type": "string"
                  },
                  "logLevel": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  },
                  "timestamp": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "logs"
        ],
        "summary": "Saves a log to the datastore",
        "operationId": "saveLog",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "eventId": {
                    "type": "string"
                  },
                  "keptnContext": {
                    "type": "string"
                  },
                  "keptnService": {
                    "type": "string"
                  },
                  "logLevel": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  },
                  "timestamp": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/logs/eventId/{eventId}": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "Get logs by eventId",
        "operationId": "getLogsByEventId",
        "parameters": [
          {
            "type": "string",
            "description": "EventId of the event the logs belog to",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "eventId": {
                    "type": "string"
                  },
                  "keptnContext": {
                    "type": "string"
                  },
                  "keptnService": {
                    "type": "string"
                  },
                  "logLevel": {
                    "type": "string"
                  },
                  "message": {
                    "type": "string"
                  },
                  "timestamp": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "fields": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "KeptnContextExtendedCE": {
      "allOf": [
        {
          "type": "object",
          "required": [
            "specversion",
            "id",
            "type",
            "source"
          ],
          "properties": {
            "contenttype": {
              "type": "string"
            },
            "data": {
              "type": [
                "object",
                "string"
              ]
            },
            "extensions": {
              "type": "object"
            },
            "id": {
              "type": "string"
            },
            "source": {
              "type": "string",
              "format": "uri-reference"
            },
            "specversion": {
              "type": "string"
            },
            "time": {
              "type": "string",
              "format": "date-time"
            },
            "type": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "shkeptncontext": {
              "type": "string"
            }
          }
        }
      ]
    },
    "LogEntry": {
      "type": "object",
      "properties": {
        "eventId": {
          "type": "string"
        },
        "keptnContext": {
          "type": "string"
        },
        "keptnService": {
          "type": "string"
        },
        "logLevel": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  }
}`))
}
