// Code generated by go-swagger; DO NOT EDIT.

package service_default_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProjectProjectNameServiceServiceNameResourceResourceURIHandlerFunc turns a function with the right signature into a get project project name service service name resource resource URI handler
type GetProjectProjectNameServiceServiceNameResourceResourceURIHandlerFunc func(GetProjectProjectNameServiceServiceNameResourceResourceURIParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProjectProjectNameServiceServiceNameResourceResourceURIHandlerFunc) Handle(params GetProjectProjectNameServiceServiceNameResourceResourceURIParams) middleware.Responder {
	return fn(params)
}

// GetProjectProjectNameServiceServiceNameResourceResourceURIHandler interface for that can handle valid get project project name service service name resource resource URI params
type GetProjectProjectNameServiceServiceNameResourceResourceURIHandler interface {
	Handle(GetProjectProjectNameServiceServiceNameResourceResourceURIParams) middleware.Responder
}

// NewGetProjectProjectNameServiceServiceNameResourceResourceURI creates a new http.Handler for the get project project name service service name resource resource URI operation
func NewGetProjectProjectNameServiceServiceNameResourceResourceURI(ctx *middleware.Context, handler GetProjectProjectNameServiceServiceNameResourceResourceURIHandler) *GetProjectProjectNameServiceServiceNameResourceResourceURI {
	return &GetProjectProjectNameServiceServiceNameResourceResourceURI{Context: ctx, Handler: handler}
}

/* GetProjectProjectNameServiceServiceNameResourceResourceURI swagger:route GET /project/{projectName}/service/{serviceName}/resource/{resourceURI} Service Default Resource getProjectProjectNameServiceServiceNameResourceResourceUri

Get the specified default resource for the service

*/
type GetProjectProjectNameServiceServiceNameResourceResourceURI struct {
	Context *middleware.Context
	Handler GetProjectProjectNameServiceServiceNameResourceResourceURIHandler
}

func (o *GetProjectProjectNameServiceServiceNameResourceResourceURI) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProjectProjectNameServiceServiceNameResourceResourceURIParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
