// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/keptn/keptn/shipyard-controller/models"
)

// HandleEventOKCode is the HTTP code returned for type HandleEventOK
const HandleEventOKCode int = 200

/*HandleEventOK OK

swagger:response handleEventOK
*/
type HandleEventOK struct {
}

// NewHandleEventOK creates HandleEventOK with default headers values
func NewHandleEventOK() *HandleEventOK {

	return &HandleEventOK{}
}

// WriteResponse to the client
func (o *HandleEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*HandleEventDefault Error

swagger:response handleEventDefault
*/
type HandleEventDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewHandleEventDefault creates HandleEventDefault with default headers values
func NewHandleEventDefault(code int) *HandleEventDefault {
	if code <= 0 {
		code = 500
	}

	return &HandleEventDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the handle event default response
func (o *HandleEventDefault) WithStatusCode(code int) *HandleEventDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the handle event default response
func (o *HandleEventDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the handle event default response
func (o *HandleEventDefault) WithPayload(payload *models.Error) *HandleEventDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the handle event default response
func (o *HandleEventDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HandleEventDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
