// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KeptnContext keptn context
// swagger:model keptnContext
type KeptnContext struct {

	// keptn context
	// Required: true
	KeptnContext *string `json:"keptnContext"`
}

// Validate validates this keptn context
func (m *KeptnContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeptnContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeptnContext) validateKeptnContext(formats strfmt.Registry) error {

	if err := validate.Required("keptnContext", "body", m.KeptnContext); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *KeptnContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeptnContext) UnmarshalBinary(b []byte) error {
	var res KeptnContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
