// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/keptn/keptn/configuration-service/models"
)

// GetProjectProjectNameStageStageNameServiceServiceNameOKCode is the HTTP code returned for type GetProjectProjectNameStageStageNameServiceServiceNameOK
const GetProjectProjectNameStageStageNameServiceServiceNameOKCode int = 200

/*GetProjectProjectNameStageStageNameServiceServiceNameOK Success

swagger:response getProjectProjectNameStageStageNameServiceServiceNameOK
*/
type GetProjectProjectNameStageStageNameServiceServiceNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Service `json:"body,omitempty"`
}

// NewGetProjectProjectNameStageStageNameServiceServiceNameOK creates GetProjectProjectNameStageStageNameServiceServiceNameOK with default headers values
func NewGetProjectProjectNameStageStageNameServiceServiceNameOK() *GetProjectProjectNameStageStageNameServiceServiceNameOK {

	return &GetProjectProjectNameStageStageNameServiceServiceNameOK{}
}

// WithPayload adds the payload to the get project project name stage stage name service service name o k response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameOK) WithPayload(payload *models.Service) *GetProjectProjectNameStageStageNameServiceServiceNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project project name stage stage name service service name o k response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameOK) SetPayload(payload *models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectProjectNameStageStageNameServiceServiceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProjectProjectNameStageStageNameServiceServiceNameNotFoundCode is the HTTP code returned for type GetProjectProjectNameStageStageNameServiceServiceNameNotFound
const GetProjectProjectNameStageStageNameServiceServiceNameNotFoundCode int = 404

/*GetProjectProjectNameStageStageNameServiceServiceNameNotFound Failed. Service could not be found.

swagger:response getProjectProjectNameStageStageNameServiceServiceNameNotFound
*/
type GetProjectProjectNameStageStageNameServiceServiceNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetProjectProjectNameStageStageNameServiceServiceNameNotFound creates GetProjectProjectNameStageStageNameServiceServiceNameNotFound with default headers values
func NewGetProjectProjectNameStageStageNameServiceServiceNameNotFound() *GetProjectProjectNameStageStageNameServiceServiceNameNotFound {

	return &GetProjectProjectNameStageStageNameServiceServiceNameNotFound{}
}

// WithPayload adds the payload to the get project project name stage stage name service service name not found response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameNotFound) WithPayload(payload *models.Error) *GetProjectProjectNameStageStageNameServiceServiceNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project project name stage stage name service service name not found response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectProjectNameStageStageNameServiceServiceNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetProjectProjectNameStageStageNameServiceServiceNameDefault Error

swagger:response getProjectProjectNameStageStageNameServiceServiceNameDefault
*/
type GetProjectProjectNameStageStageNameServiceServiceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetProjectProjectNameStageStageNameServiceServiceNameDefault creates GetProjectProjectNameStageStageNameServiceServiceNameDefault with default headers values
func NewGetProjectProjectNameStageStageNameServiceServiceNameDefault(code int) *GetProjectProjectNameStageStageNameServiceServiceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetProjectProjectNameStageStageNameServiceServiceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get project project name stage stage name service service name default response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameDefault) WithStatusCode(code int) *GetProjectProjectNameStageStageNameServiceServiceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get project project name stage stage name service service name default response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get project project name stage stage name service service name default response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameDefault) WithPayload(payload *models.Error) *GetProjectProjectNameStageStageNameServiceServiceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get project project name stage stage name service service name default response
func (o *GetProjectProjectNameStageStageNameServiceServiceNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProjectProjectNameStageStageNameServiceServiceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
