// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fake

import (
	"github.com/keptn/go-utils/pkg/api/models"
	api "github.com/keptn/go-utils/pkg/api/utils"
	"github.com/keptn/keptn/webhook-service/handler"
	"sync"
)

// Ensure, that IResourceHandlerMock does implement handler.IResourceHandler.
// If this is not the case, regenerate this file with moq.
var _ handler.IResourceHandler = &IResourceHandlerMock{}

// IResourceHandlerMock is a mock implementation of handler.IResourceHandler.
//
// 	func TestSomethingThatUsesIResourceHandler(t *testing.T) {
//
// 		// make and configure a mocked handler.IResourceHandler
// 		mockedIResourceHandler := &IResourceHandlerMock{
// 			GetResourceFunc: func(scope api.ResourceScope, options ...api.URIOption) (*models.Resource, error) {
// 				panic("mock out the GetResource method")
// 			},
// 		}
//
// 		// use mockedIResourceHandler in code that requires handler.IResourceHandler
// 		// and then make assertions.
//
// 	}
type IResourceHandlerMock struct {
	// GetResourceFunc mocks the GetResource method.
	GetResourceFunc func(scope api.ResourceScope, options ...api.URIOption) (*models.Resource, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetResource holds details about calls to the GetResource method.
		GetResource []struct {
			// Scope is the scope argument value.
			Scope api.ResourceScope
			// Options is the options argument value.
			Options []api.URIOption
		}
	}
	lockGetResource sync.RWMutex
}

// GetResource calls GetResourceFunc.
func (mock *IResourceHandlerMock) GetResource(scope api.ResourceScope, options ...api.URIOption) (*models.Resource, error) {
	if mock.GetResourceFunc == nil {
		panic("IResourceHandlerMock.GetResourceFunc: method is nil but IResourceHandler.GetResource was just called")
	}
	callInfo := struct {
		Scope   api.ResourceScope
		Options []api.URIOption
	}{
		Scope:   scope,
		Options: options,
	}
	mock.lockGetResource.Lock()
	mock.calls.GetResource = append(mock.calls.GetResource, callInfo)
	mock.lockGetResource.Unlock()
	return mock.GetResourceFunc(scope, options...)
}

// GetResourceCalls gets all the calls that were made to GetResource.
// Check the length with:
//     len(mockedIResourceHandler.GetResourceCalls())
func (mock *IResourceHandlerMock) GetResourceCalls() []struct {
	Scope   api.ResourceScope
	Options []api.URIOption
} {
	var calls []struct {
		Scope   api.ResourceScope
		Options []api.URIOption
	}
	mock.lockGetResource.RLock()
	calls = mock.calls.GetResource
	mock.lockGetResource.RUnlock()
	return calls
}
